#!/usr/bin/env bash
# installs nginx web server


echo -e "Updating and installing Nginx.\n"
apt-get update -y -qq && \
	apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# starting nginx service
service nginx start

# allowing nginx on firewall
ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
chown -R "$USER":"$USER" /var/www/html
chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.html /var/www/html/index.html.bckp

# Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.html

# Restarting nginx
service nginx restart

echo -e "\nCompleted. ✅\n"
