#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"

frontend ouafcode-frontend
	bind *:80
	mode http
	default_backend ouafcode-backend
backend ouafcode-backend
	balance roundrobin
	server 293540-web-01 54.173.247.174:80 check
	server 293540-web-02 100.24.72.14:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
